language: node_js
node_js: "stable"
cache:
  yarn: true
  directories: 
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local_dir: dist
  on:
    branch: master