language: node_js
node_js: "stable"

cache:
  yarn: true
  directories: 
  - node_modules

script:
  - yarn
  - yarn build

# Deploy to gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local_dir: dist
  on:
    branch: master

# Deploy to surge
deploy:
  provider: surge
  project: dist
  domain: https://fun-with-web-components.surge.sh
